version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sistema_ponto_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - sistema_ponto_network
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: sistema_ponto_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - sistema_ponto_network
        depends_on:
            - app

    db:
        image: postgres:15-alpine
        container_name: sistema_ponto_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: sistema_ponto
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: acesse
        ports:
            - "5433:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - sistema_ponto_network

networks:
    sistema_ponto_network:
        driver: bridge

volumes:
    dbdata:
        driver: local
